#! /bin/bash
EXEC=../dist/runtime
TMP=/var/tmp

args=("$@")
opts=("${args[@]:1}")

function assert_eq () {
    result=`$EXEC ${opts[@]} -s -e "$1"`

    if [ $? -eq 0 ]
    then
       if [ "$result" != "$2" ]
       then
           echo -e "$1","$2","$result",failed
       else
           echo -e "$1","$2","$result",passed
       fi
    else
        echo -e "$1",aborted
    fi
}

source "$1" >> $TMP/dyad-test.$$.log 2>&1

total=`cat $1 | wc -l`
failed=`grep failed $TMP/dyad-test.$$.log | wc -l`
aborted=`grep aborted $TMP/dyad-test.$$.log | wc -l`
file=`basename "$1"`

echo "mu:",$file,$total,$failed,$aborted
cat $TMP/dyad-test.$$.log

rm -f $TMP/dyad-test.$$.log

exit 0
